### ISSUE TITLE
Weight increasing dramatically on its own

### ISSUE THREAD

**Issue by riskitforabiscuit1252** [markusressel/ESPHome-Smart-Scale#14] opened 2023-06-12 16:47 UTC
Hi Mark,

I’ve been using your code for a bed sensor for a good few months now and it has been fantastic! 

Recently, however, the weights have just been going up do absolutely no reason at all. You can see this from the screenshot, me and my partner were in bed from around midnight to around 9am and no one has been bed since. Yet, the weight has continued to over 300kg at one point! The drops to zero on the graph are when I have just manually had to tare the scale. 

It has hit summer over the here in the uk and the temperatures have increased dramatically over the past week especially and I’m thinking that this may potentially be the issue unless you have some other ideas? Could it be a Esphome update for the esp8266 that I installed? (On a side note: should I stay away from these updates in the future or do you find them safe in your experience?)

Do you have any advice on how to help the situation? Would recalibrating the scale during this increased heat help? Or maybe downgrading the software back? Would love to hear your thoughts as it’s made the bed occupancy currently unusable.

**Comment by markusressel** [comment] 2023-06-13 01:06
Your load cells are failing. I had the same issue on my bed sensor and havent gotten around to a fix since then. Due to the continuous load, which is s substantial percentage of the total rated capacity, the metal bends kver time, leading to false readings. I guess those load cells are not meant to be used in a scenario with continuous load appllied to them. You can try to fix it by using beefier load cells or distributing the weight along more load cells/points to relief some stress, but no guarantees.

**Comment by riskitforabiscuit1252** [comment] 2023-07-20 19:42
> Your load cells are failing. I had the same issue on my bed sensor and havent gotten around to a fix since then. Due to the continuous load, which is s substantial percentage of the total rated capacity, the metal bends kver time, leading to false readings. I guess those load cells are not meant to be used in a scenario with continuous load appllied to them. You can try to fix it by using beefier load cells or distributing the weight along more load cells/points to relief some stress, but no guarantees.

Cheers of getting back to me, know of any other beefier load cells you can recommend?

**Comment by philder** [comment] 2024-02-09 04:43
Hi @markusressel thank you for your time developing this project. I bring this issue up because I'm having the same problem. I have brand new 4 load cells (50kg) between bed and mattress last 2 days and values float from -145000 and -125000 from initial zero. The only load I have is the mattress that weights 40kg. I also tried auto tare but I keep getting false triggers. Can you please help? Thank you!

**Comment by markusressel** [comment] 2024-04-08 17:37
There is no generic solution, and the problem is not caused by ESPHome-Smart-Scale. If you measure the raw values produced by the load cell you will see that it has permanently changed behavior. This can only be caused by overloading or otherwise damaging the load cells.

Since there is no way to fix through this repo, I am going to close this issue now.

**Closed by markusressel** 2024-04-08 17:37 UTC
Labels: documentation
